### ISSUE TITLE
[beta] Update JS stubs

### ISSUE THREAD

**Issue by altafan** [TDex-network/tdex-protobuf#17]
The last commit 6b2290faf9b6d06167be7feedf7748291778c77f does not contain JS generated stubs since I'm not able to run `make js` since it always returns me an error `dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin` when running `grpc_tools_node_protoc`. Didn't find a way to make it working. Please, update JS stubs.

**Comment by tiero** [comment]
Should be closed by https://github.com/TDex-network/tdex-protobuf/commit/fc06399d7707b8830e1875b4f5cabc57fcdf1b83
